apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: replicatedstatefulsets.clusterlabs.org
spec:
  group: clusterlabs.org
  names:
    kind: ReplicatedStatefulSet
    listKind: ReplicatedStatefulSetList
    plural: replicatedstatefulsets
    shortNames:
    - rss
    singular: replicatedstatefulset
  scope: Namespaced
  version: v1alpha1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rss-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rss-operator
    spec:
      containers:
      - name: rss-operator
        image: quay.io/beekhof/rss-operator:latest
        imagePullPolicy: Always
#        restartPolicy: Never
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
---
apiVersion: clusterlabs.org/v1alpha1
kind: ReplicatedStatefulSet
metadata:
  name: dummy
spec:
  replicas: 3
  pod:
    antiAffinity: true
    commands:
      sequence: 
        command: ["/sequence.sh"]
      primary: 
        command: ["/start.sh"]
      seed: 
        command: ["/seed.sh"]
      status: 
        timeout: 60s
        command: ["/check.sh"]
      stop: 
        command: ["/stop.sh"]
    containers:
    - name: dummy
      image: quay.io/beekhof/dummy:latest
      imagePullPolicy: Always
  service:
    name: dummy-svc
    sessionAffinity: None
