apiVersion: "galera.database.beekhof.net/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example"
spec:
  size: 3
  TLS:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls

