# An example of connecting to Ceph for shared storage
#
# My ceph nodes happen to be: ceph2-[1..3]
# The required secrets can be populated by running:
#
#   cat ceph.client.admin.keyring | tail -n 1 | awk '{print $3}' >> admin.secret
#   kubectl create secret generic ceph-secret-admin --type="kubernetes.io/rbd" --from-file=admin.secret --namespace=kube-system
#
apiVersion: v1
data:
  admin.secret: QVFBQkt5VmF0K0FhSXhBQU5xcElISnlZY2krQ2t6UFNsNWpZQ1E9PQo=
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: kube-system
type: kubernetes.io/rbd
