#
# Normally the operator will populate this, but it helps avoid timing errors
# if we pre-populate it before testing
#
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: replicatedstatefulsets.clusterlabs.org
spec:
  group: clusterlabs.org
  names:
    kind: ReplicatedStatefulSet
    listKind: ReplicatedStatefulSetList
    plural: replicatedstatefulsets
    shortNames:
    - rss
    singular: replicatedstatefulset
  scope: Namespaced
  version: v1alpha1
