apiVersion: clusterlabs.org/v1alpha1
kind: ReplicatedStatefulSet
metadata:
  # https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#idempotency
  name: example
  labels:
    kind: dummy
spec:
  replicas: 3
  chaosLevel: 0
  pod:
    antiAffinity: true
    commands:
      sequence: 
        timeout: 20s
        command: ["/sequence.sh"]
      primary: 
        command: ["/start.sh"]
      seed: 
        command: ["/seed.sh"]
      status: 
        timeout: 2m
        command: ["/check.sh"]
      stop: 
        command: ["/stop.sh"]
    containers:
    - name: dummy
      image: quay.io/beekhof/dummy:latest
      imagePullPolicy: Always
