apiVersion: v1
kind: Pod
metadata:
  name: rss-operator
spec:
  containers:
  - name: operator
    image: quay.io/beekhof/rss-operator:latest
    # Defaults to just '/usr/local/bin/rss-operator' but show debug logs in the example
    command: [ "/usr/local/bin/rss-operator", "-alsologtostderr", "-v", "1" ]
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
