# An example of connecting to Ceph for shared storage
#
# My ceph nodes happen to be: ceph2-[1..3]
# The required secrets can be populated by running:
#
#   cat ceph.client.admin.keyring | tail -n 1 | awk '{print $3}' >> admin.secret
#   kubectl create secret generic ceph-secret-admin --type="kubernetes.io/rbd" --from-file=admin.secret --namespace=kube-system
#   kubectl create secret generic ceph-secret-user --type="kubernetes.io/rbd" --from-file=admin.secret
#
apiVersion: v1
data:
  admin.secret: QVFBQkt5VmF0K0FhSXhBQU5xcElISnlZY2krQ2t6UFNsNWpZQ1E9PQo=
kind: Secret
metadata:
  name: ceph-secret-user
type: kubernetes.io/rbd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
parameters:
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: kube-system
  fsType: ext4
  imageFeatures: layering
  imageFormat: "1"
  monitors: ceph2-1:6789,ceph2-2:6789,ceph2-3:6789
  pool: rbd
  userId: admin
  userSecretName: ceph-secret-user
provisioner: kubernetes.io/rbd
reclaimPolicy: Delete
#---
# Example Claim
#
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: my-storage-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
#   storageClassName: my-storage-class
