apiVersion: "galera.database.beekhof.net/v1alpha1"
kind: "GaleraBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  clusterName: example-etcd-cluster
  storageType: S3
  s3:
    s3Bucket: <s3-bucket-name>
    awsSecret: <aws-secret>
