apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: replicatedstatefulsets.clusterlabs.org
spec:
  group: clusterlabs.org
  names:
    kind: ReplicatedStatefulSet
    listKind: ReplicatedStatefulSetList
    plural: replicatedstatefulsets
    shortNames:
    - rss
    singular: replicatedstatefulset
  scope: Namespaced
  version: v1alpha1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rss-operator
  # labels:
  #   name: rss-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rss-operator
    spec:
      containers:
      - name: rss-operator
        image: quay.io/beekhof/rss-operator:latest
        imagePullPolicy: Always
        # restartPolicy: Never
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
---
apiVersion: clusterlabs.org/v1alpha1
kind: ReplicatedStatefulSet
metadata:
  # https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#idempotency
  generateName: galera-
  labels:
    kind: galera
spec:
  replicas: 3
  pod:
    antiAffinity: true
  service:
    name: galera-svc
    sessionAffinity: None
  serviceName: galera-svc
  servicePorts:
  - name: galera
    port: 13306
    targetPort: 3306
    # https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
  volumes:
  - emptyDir: {}
    name: galera-db
  externalIPs:
  - 192.168.124.101
  containers:
  - name: rss
    image: quay.io/beekhof/galera:latest
    imagePullPolicy: Always
    # env:
    # - name: SOME_POD_NAMESPACE
    #   valueFrom:
    #     fieldRef:
    #       apiVersion: v1
    #       fieldPath: metadata.namespace
    ports:
    - containerPort: 3306
      name: galera
      protocol: TCP
     # http://galeracluster.com/documentation-webpages/firewallsettings.html
      # 3306 For MySQL client connections and State Snapshot Transfer that use the mysqldump method.
      # 4567 For Galera Cluster replication traffic, multicast replication uses both UDP transport and TCP on this port.
      # 4568 For Incremental State Transfer.
      # 4444 For all other State Snapshot Transfer.
    volumeMounts:
    - mountPath: /var/galera/data
      name: galera-db
  commands:
    sequence:
    - /sequence.sh
    primary:
    - /start.sh
    seed:
    - /seed.sh
    status:
    - /check.sh
    stop:
    - /stop.sh
