apiVersion: clusterlabs.org/v1alpha1
kind: ReplicatedStatefulSet
metadata:
  # https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#idempotency
  generateName: galera-
  labels:
    kind: galera
spec:
  replicas: 3
  pod:
    antiAffinity: true
    commands:
      sequence: 
        command: ["/sequence.sh"]
      primary: 
        command: ["/start.sh"]
      seed: 
        command: ["/seed.sh"]
      status: 
        timeout: 60
        command: ["/check.sh"]
      stop: 
        command: ["/stop.sh"]
    containers:
    - name: rss
      image: quay.io/beekhof/galera:latest
      imagePullPolicy: Always
      lifecycle:
        preStop:
            exec:
              command: ["/stop.sh"]
      ports:
      - containerPort: 3306
        name: galera
        protocol: TCP
      - containerPort: 4567
        name: galera-rep
        protocol: TCP
      - containerPort: 4568
        name: galera-state
        protocol: TCP
      - containerPort: 4444
        name: galera-snap
        protocol: TCP
        # http://galeracluster.com/documentation-webpages/firewallsettings.html
        # 3306 For MySQL client connections and State Snapshot Transfer that use the mysqldump method.
        # 4567 For Galera Cluster replication traffic, multicast replication uses both UDP transport and TCP on this port.
        # 4568 For Incremental State Transfer.
        # 4444 For all other State Snapshot Transfer.
  service:
    serviceName: galera-svc
    sessionAffinity: None
    servicePorts:
    - name: galera
      port: 13306
      targetPort: 3306
      # https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
